name: Deploy to S3

on:
  push:
    branches:
      - develop

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate HTML
      run: |
        echo "Validating HTML"
        # Add any HTML validation commands here if needed
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://my-static-prodwebapp --exclude ".git/*" --delete

    - name: Set public-read ACL
      run: |
        aws s3 cp s3://my-static-website-demo1/index.html s3://my-static-website-demo1/index.html --acl public-read
